enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&D&lDREADPIXEL &f[1.8-1.20] &b&lRelease &f| &7dreadpixel.aifos.cl&r\n'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 75
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: af584477-4f1f-47f1-8934-cbf46c3b04e7
player_limit: 75
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: dynamic-9.magmanode.com:25684
    motd: '&7// &cDreadPixel Network &7//'
    restricted: false
  skyblock:
    address: extreme7z8a.creepercloud.io:26430
    motd: '&7// &cDreadPixel Network &7//'
    restricted: false
